language: java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://mattermost.synaptix-labs.com/hooks/qxuodwiqwbytpqg74u8eb1yfoy
#    on_success: [always|never|change] # default: always
#    on_failure: [always|never|change] # default: always
#    on_start: [always|never|change] # default: always